/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dto;

import gp.Pelicula;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Santos Castillo
 */
public class ListaPeliculas extends javax.swing.JDialog {

    Menu menu;

    public ListaPeliculas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        menu = (Menu) parent;
        inicializarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnAnyadir = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAnyadir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAnyadir.setText("Añadir");
        btnAnyadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnyadirActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnEditar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditar1.setText("Editar");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnyadir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnyadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAnyadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnyadirActionPerformed

        Anyadir1 anyadir = new Anyadir1(this, true);

        anyadir.setVisible(true);

    }//GEN-LAST:event_btnAnyadirActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        int res;

        if (validarFormulario()) {

            res = JOptionPane.showConfirmDialog(this, "¿Esta seguro de que desea realizar esta operación?", "Confirmación", JOptionPane.YES_NO_OPTION);

            if (res == JOptionPane.YES_OPTION) {

                borraryRefrescar();

                JOptionPane.showMessageDialog(this, "Confirmado", "Confirmado", JOptionPane.INFORMATION_MESSAGE);

            }

        }


    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed

        if (validarFormulario()) {

            Editar1 editar = new Editar1(this, true);

            editar.setVisible(true);

        }


    }//GEN-LAST:event_btnEditar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void inicializarTabla() {

        DefaultTableModel dtm = new DefaultTableModel();

        dtm.setColumnIdentifiers(new String[]{"Nombre", "Género", "Estreno", "Director", "Nacionalidad"});

        for (Pelicula pelicula : menu.ldn.getPeliculas()) {

            dtm.addRow(pelicula.toArrayString());

        }

        jTable1.setModel(dtm);

    }

    public String getNombre() {

        return (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);

    }

    public String getGenero() {

        return (String) jTable1.getValueAt(jTable1.getSelectedRow(), 1);

    }

    public Date getFecha() {

        Date fecha = null;

        try {
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

            fecha = format.parse((String) (jTable1.getValueAt(jTable1.getSelectedRow(), 2)));
        } catch (ParseException ex) {
            Logger.getLogger(ListaPeliculas.class.getName()).log(Level.SEVERE, null, ex);
        }

        return fecha;
    }

    public String getDirector() {

        return (String) jTable1.getValueAt(jTable1.getSelectedRow(), 3);

    }

    public String getPais() {

        return (String) jTable1.getValueAt(jTable1.getSelectedRow(), 4);

    }

    public int getIndex() {

        return jTable1.getSelectedRow();

    }

    public boolean validarFormulario() {

        if (menu.ldn.totalPeliculas() == 0) {

            JOptionPane.showMessageDialog(this, "No hay peliculas en la Base de Datos", "Error: sin peliculas", JOptionPane.ERROR_MESSAGE);

            return false;

        }

        if (getIndex() >= 0) {

            return true;

        } else {

            JOptionPane.showMessageDialog(this, "No se seleccionado ninguna fila.", "Error: fila no especificada", JOptionPane.ERROR_MESSAGE);

            return false;

        }

    }

    public void borraryRefrescar() {

        Pelicula pelicula = menu.ldn.getPeliculas().get(getIndex());

        menu.ldn.borrarPelicula(pelicula);

        inicializarTabla();

        menu.refrescarContador();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnyadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
